version: '2'
services:
    webphp7:
        build: 
            context: ./docker/web7
            dockerfile: Dockerfile
        ports:
            - 8087:80
            - 447:443
        volumes:
            - ./sources:/var/www/html
            - ./docker/MyParams.php:/var/www/html/commun/MyParams.php
            - ./docker/MyConfig.php:/var/www/html/commun/MyConfig.php
            - ./docker/error7.log:/var/log/apache2/error.log
        environment:
            - ALLOW_OVERRIDE=true
        links:
            - db
            - mailcatcher
    db:
        build: 
            context: ./docker/db
            dockerfile: Dockerfile
        image: mysql:latest
        restart: always
        command: mysqld --sql_mode=""
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: my_admin
            MYSQL_PASSWORD: my_passwd
            MYSQL_DATABASE: my_database
        ports:
            - 3306:3306
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        links:
            - db
    mailcatcher:
        image: schickling/mailcatcher
        # ports:
        #     - 1025:1025
        #     - 8025:8025