ARG BASE_IMAGE_PHP
ARG USER_ID
ARG GROUP_ID

FROM ${BASE_IMAGE_PHP}

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y libonig-dev mailutils msmtp nano \
    && docker-php-ext-install pdo pdo_mysql mbstring \
    && a2enmod headers \
    && a2enmod expires \
    && a2enmod rewrite \
    && service apache2 restart

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
