name: '${APPLICATION_NAME}'
services:
    kpi:
        container_name: ${PHP_CONTAINER_NAME}
        build:
            context: ./config
            dockerfile: Dockerfile.dev.web
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                BASE_IMAGE_PHP: ${BASE_IMAGE_PHP}
        user: ${USER_ID}:${GROUP_ID}
        # ports:
        #     - 80${DOCKER_SUFFIXE_PORT}:80
        volumes:
            - ../sources:/var/www/html
            - ./MyParams.php:/var/www/html/commun/MyParams.php
            - ./MyConfig.php:/var/www/html/commun/MyConfig.php
            - ${HOST_APACHE2_LOG_PATH}:/var/log/apache2/
        networks:
            - network_kpi
            - traefiknetwork
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kpi.rule=Host(`kpi.local`) && PathPrefix(`/`)"
            - "traefik.http.routers.kpi.entrypoints=websecure"
            - "traefik.http.routers.kpi.tls=true"
    db:
        container_name: ${DB_CONTAINER_NAME}
        build:
            context: ./config
            dockerfile: Dockerfile.db
            args:
                BASE_IMAGE_DB: ${BASE_IMAGE_DB}
        command: mysqld --sql_mode=""
        volumes:
            - ${HOST_DB_PATH}:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        # ports:
        #     - 33${DOCKER_SUFFIXE_PORT}:3306
        networks:
            - network_kpi
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
    myadmin:
        container_name: ${MYADMIN_CONTAINER_NAME}
        image: phpmyadmin/phpmyadmin:latest
        environment:
            # 256 Mo
            UPLOAD_LIMIT: 262144000
        # ports:
        #     - 81${DOCKER_SUFFIXE_PORT}:80
        depends_on:
            - db
        networks:
            - network_kpi
            - traefiknetwork
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
        volumes:
            - ./config/config.dev.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.myadmin.rule=Host(`kpi.local`) && PathPrefix(`/myadmin`)"
            - "traefik.http.routers.myadmin.middlewares=strip-myadmin-prefix"
            - "traefik.http.middlewares.strip-myadmin-prefix.stripprefix.prefixes=/myadmin"
            - "traefik.http.routers.myadmin.entrypoints=websecure"
            - "traefik.http.routers.myadmin.tls=true"

networks:
    network_kpi:
        external: true
        name: network_${APPLICATION_NAME}
    traefiknetwork:
        name: traefiknetwork
        external: true