name: '${APPLICATION_NAME}'
services:
    kpi:
        container_name: ${PHP_CONTAINER_NAME}
        build:
            context: ./config
            dockerfile: Dockerfile.dev.web
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                BASE_IMAGE_PHP: ${BASE_IMAGE_PHP}
        user: ${USER_ID}:${GROUP_ID}
        ports:
            - 80${DOCKER_SUFFIXE_PORT}:80
        volumes:
            - ../sources:/var/www/html
            - ./MyParams.php:/var/www/html/commun/MyParams.php
            - ./MyConfig.php:/var/www/html/commun/MyConfig.php
            - ${HOST_APACHE2_LOG_PATH}:/var/log/apache2/
        networks:
            - network_kpi
            - traefiknetwork
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kpi.rule=Host(`${KPI_DOMAIN_NAME}`)"
            - "traefik.http.routers.kpi.entrypoints=websecure"
            - "traefik.http.routers.kpi.tls=true"
    kpi8:
        container_name: ${PHP_CONTAINER_NAME}8
        build:
            context: ./config
            dockerfile: Dockerfile.dev.web
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                BASE_IMAGE_PHP: ${BASE_IMAGE_PHP_8}
        user: ${USER_ID}:${GROUP_ID}
        ports:
            - 88${DOCKER_SUFFIXE_PORT}:80
        volumes:
            - ../sources:/var/www/html
            - ./MyParams.php:/var/www/html/commun/MyParams.php
            - ./MyConfig.php:/var/www/html/commun/MyConfig.php
            - ${HOST_APACHE2_LOG_PATH_8}:/var/log/apache2/
        networks:
            - network_kpi
            - traefiknetwork
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kpi8.rule=Host(`${KPI_DOMAIN_NAME_8}`)"
            - "traefik.http.routers.kpi8.entrypoints=websecure"
            - "traefik.http.routers.kpi8.tls=true"
    db:
        container_name: ${DB_CONTAINER_NAME}
        build:
            context: ./config
            dockerfile: Dockerfile.db
            args:
                BASE_IMAGE_DB: ${BASE_IMAGE_DB}
        command: mysqld --sql_mode=""
        volumes:
            - ${HOST_DB_PATH}:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        # ports:
        #     - 33${DOCKER_SUFFIXE_PORT}:3306
        networks:
            - network_kpi
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
    dbwp:
        container_name: ${DBWP_CONTAINER_NAME}
        build:
            context: ./config
            dockerfile: Dockerfile.db
            args:
                BASE_IMAGE_DB: ${BASE_IMAGE_DB}
        volumes:
            - ${HOST_DBWP_PATH}:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${DBWP_ROOT_PASSWORD}
            MYSQL_USER: ${DBWP_USER}
            MYSQL_PASSWORD: ${DBWP_PASSWORD}
            MYSQL_DATABASE: ${DBWP_NAME}
        # ports:
        #     - 33${DOCKER_SUFFIXE_PORT}:3306
        networks:
            - network_kpi
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
    myadmin:
        container_name: ${MYADMIN_CONTAINER_NAME}
        image: phpmyadmin/phpmyadmin:latest
        environment:
            # 256 Mo
            UPLOAD_LIMIT: 262144000
            PMA_HOSTS: db,dbwp
        # ports:
        #     - 81${DOCKER_SUFFIXE_PORT}:80
        depends_on:
            - db
            - dbwp
        networks:
            - network_kpi
            - traefiknetwork
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: 3
        restart: unless-stopped
        # volumes:
        #     - ./config/config.dev.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.myadmin.rule=Host(`${MYADMIN_DOMAIN_NAME}`)"
            # - "traefik.http.routers.myadmin.middlewares=redirect-slash,strip-myadmin-prefix"
            # - "traefik.http.middlewares.strip-myadmin-prefix.stripprefix.prefixes=/myadmin"
            # - "traefik.http.middlewares.redirect-slash.redirectregex.regex=^(https?://[^/]+/[^/]+)$$"
            # - "traefik.http.middlewares.redirect-slash.redirectregex.replacement=$${1}/"
            - "traefik.http.routers.myadmin.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USERS}"
            - "traefik.http.routers.myadmin.entrypoints=websecure"
            - "traefik.http.routers.myadmin.tls=true"
        
    
    # node:
    #     container_name: kpi_node
    #     # image: node:latest
    #     build:
    #         context: ../
    #         dockerfile: ./docker/node/Dockerfile
    #     ports:
    #         - "8000:8000" # vue ui
    #         - "9000:8080" # Vue-cli HMR
    #     volumes:
    #         - ../sources/app_dev:/app
    #     user: "1000:33"
    # node_live:
    #     container_name: kpi_node_live
    #     # image: node:latest
    #     build:
    #         context: ../
    #         dockerfile: ./docker/node/Dockerfile_live
    #     ports:
    #         - "8001:8000" # vue ui
    #         - "9001:8080" # Vue-cli HMR
    #     volumes:
    #         - ../sources/app_live_dev:/app
    #     user: "1000:33"
    # node_wsm:
    #     container_name: kpi_node_wsm
    #     # image: node:latest
    #     build:
    #         context: ../
    #         dockerfile: ./docker/node/Dockerfile_wsm
    #     ports:
    #         - "8002:8000" # vue ui
    #         - "9002:8080" # Vue-cli HMR
    #     volumes:
    #         - ../sources/app_wsm_dev:/app
    #     user: "1000:33"


networks:
    network_kpi:
        external: true
        name: network_${APPLICATION_NAME}
    traefiknetwork:
        name: traefiknetwork
        external: true