version: '2'
services:
    webphp7:
        build: 
            context: ./web7
            dockerfile: Dockerfile
        ports:
            - 8087:80
            - 447:443
        volumes:
            - ../sources:/var/www/html
            - ./MyParams.php:/var/www/html/commun/MyParams.php
            - ./MyConfig.php:/var/www/html/commun/MyConfig.php
            - ./error7.log:/var/log/apache2/error.log
            - ./mail.log:/var/log/msmtp.log
        environment:
            - ALLOW_OVERRIDE=true
        links:
            - db
            - mailcatcher
    db:
        build: 
            context: ./db
            dockerfile: Dockerfile
        image: mysql:latest
        restart: always
        command: mysqld --sql_mode=""
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: my_admin
            MYSQL_PASSWORD: my_passwd
            MYSQL_DATABASE: my_database
        ports:
            - 3306:3306
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            UPLOAD_LIMIT: 262144000 # 256 Mo
        ports:
            - 8080:80
        links:
            - db
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
    node:
        image: node:latest
        build:
          context: ../
          dockerfile: ./docker/node/Dockerfile
        ports:
          - "8000:8000" # vue ui
          - "9000:8080" # Vue-cli HMR
        volumes:
          - ../sources/app_dev:/app
        #   - ../sources/app:/app/dist
        user: "1000:33"
        links:
          - webphp7
    