services:
    webphp7:
        container_name: kpi_web
        build:
            context: ./web7
            dockerfile: Dockerfile-php7.4
        ports:
            - 8800:8000
            - 8087:80
            - 447:443
        volumes:
            - ../sources:/var/www/html
            - ./MyParams.php:/var/www/html/commun/MyParams.php
            - ./MyConfig.php:/var/www/html/commun/MyConfig.php
            - ./error7.log:/var/log/apache2/error.log
            - ./mail.log:/var/log/msmtp.log
        environment:
            - ALLOW_OVERRIDE=true
        extra_hosts:
            - host.docker.internal:host-gateway
    db:
        container_name: kpi_db
        image: mariadb:10.4.28
        restart: unless-stopped
        command: mysqld --sql_mode=""
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: my_admin
            MYSQL_PASSWORD: my_passwd
            MYSQL_DATABASE: my_database
        ports:
            - 3306:3306
    myadmin:
        container_name: kpi_myadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            UPLOAD_LIMIT: 262144000 # 256 Mo
        ports:
            - 8080:80
    mailcatcher:
        container_name: kpi_mailcatcher
        image: schickling/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
    node:
        container_name: kpi_node
        image: node:latest
        build:
            context: ../
            dockerfile: ./docker/node/Dockerfile
        ports:
            - "8000:8000" # vue ui
            - "9000:8080" # Vue-cli HMR
        volumes:
            - ../sources/app_dev:/app
        user: "1000:33"
    node_live:
        container_name: kpi_node_live
        image: node:20.14.0-alpine
        build:
            context: ../
            dockerfile: ./docker/node/Dockerfile_live
        ports:
            - "8001:8000" # vue ui
            - "9001:8080" # Vue-cli HMR
        volumes:
            - ../sources/app_live_dev:/app
        user: "1000:33"
    node_wsm:
        container_name: kpi_node_wsm
        image: node:latest
        build:
            context: ../
            dockerfile: ./docker/node/Dockerfile_wsm
        ports:
            - "8002:8000" # vue ui
            - "9002:8080" # Vue-cli HMR
        volumes:
            - ../sources/app_wsm_dev:/app
        user: "1000:33"
