<?php /* Smarty version 2.6.18, created on 2014-11-25 04:08:47
         compiled from pageNu.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'config_load', 'pageNu.tpl', 1, false),)), $this); ?>
<?php echo smarty_function_config_load(array('file' => '../../commun/MyLang.conf','section' => $this->_tpl_vars['lang']), $this);?>
<!DOCTYPE html><html lang="fr">	<head>		<meta charset="utf-8">		<meta name="Author" Content="LG">		<?php if ($this->_tpl_vars['bPublic']): ?>			<link rel="stylesheet" type="text/css" href="css/style.css" />			<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">			<link rel="stylesheet" type="text/css" href="css/jquery.autocomplete.css" media="screen">			<link rel="stylesheet" type="text/css" href="css/<?php echo $this->_tpl_vars['contenutemplate']; ?>
.css" />			<script language="JavaScript" type="text/javascript" src="js/jquery-1.5.2.min.js"></script>			<!--<script language="JavaScript" type="text/javascript" src="js/jquery-1.11.0.min.js"></script>-->			<!--<script language="JavaScript" type="text/javascript" src="js/jquery-ui-1.10.4.custom.min.js"></script>-->			<script language="JavaScript" type="text/javascript" src="js/jquery.autocomplete.min.js"></script>			<script language="JavaScript" type="text/javascript" src="js/jquery.maskedinput.min.js"></script>			<?php echo '				<script type="text/javascript">					jQuery(function($){					   $.mask.definitions[\'~\']=\'[+-]\';					   $(".time").mask("99:99");					});				</script>			'; ?>
			<script language="JavaScript" type="text/javascript" src="js/formTools.js"></script>			<script language="JavaScript" type="text/javascript" src="js/<?php echo $this->_tpl_vars['contenutemplate']; ?>
.js"></script>		<?php else: ?>			<link rel="stylesheet" type="text/css" href="../css/GestionStyle.css" />			<link rel="shortcut icon" type="image/x-icon" href="../favicon.ico">			<link rel="stylesheet" type="text/css" href="../css/jquery.autocomplete.css" media="screen">			<link rel="stylesheet" type="text/css" href="../css/<?php echo $this->_tpl_vars['contenutemplate']; ?>
.css" />			<script language="JavaScript" type="text/javascript" src="../js/jquery-1.5.2.min.js"></script>			<!--<script language="JavaScript" type="text/javascript" src="../js/jquery-1.11.0.min.js"></script>-->			<!--<script language="JavaScript" type="text/javascript" src="../js/jquery-ui-1.10.4.custom.min.js"></script>-->			<script language="JavaScript" type="text/javascript" src="../js/jquery.autocomplete.min.js"></script>			<script language="JavaScript" type="text/javascript" src="../js/jquery.maskedinput.min.js"></script>			<?php echo '				<script type="text/javascript">					jQuery(function($){					   $.mask.definitions[\'~\']=\'[+-]\';					   $(".time").mask("99:99");					});				</script>			'; ?>
			<script language="JavaScript" type="text/javascript" src="../js/formTools.js"></script>			<script language="JavaScript" type="text/javascript" src="../js/<?php echo $this->_tpl_vars['contenutemplate']; ?>
.js"></script>		<?php endif; ?>		<title><?php echo $this->_tpl_vars['title']; ?>
</title>	</head>	  	<body onload="testframe(); alertMsg('<?php echo $this->_tpl_vars['AlertMessage']; ?>
')">		<?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => ($this->_tpl_vars['contenutemplate']).".tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?>	</body></html>